### PR TITLE
feat: Dockerize application and rename Poetry script

### LINKED ISSUE #29: Containerize the application
Ensure the application can be run in a suitable container (Docker).
Part of the containerization is to handle storage of scraped data, but for this issue it is enough to write the data to some mounted volume. Writing to DB or S3-bucket will be handled in a separate issue.

### PR DESCRIPTION
**Pull request by ErikThorsell**
* Add Python 3.9.4 based docker image with separate build and runtime
  parts.
* Create separate docker/ directory to hold container specific config

Closes #29

### CODE REVIEW

**Comment by ErikThorsell** [comment]
I thought about testing of Docker images and found [this link](https://medium.com/@renatomefi/unit-testing-writing-dockerfiles-like-a-software-developer-1759f416ce84). Have you (@lindhe or @Jassob) had any experience with any similar framework?

**Comment by Jassob** [comment]
> I thought about testing of Docker images and found [this link](https://medium.com/@renatomefi/unit-testing-writing-dockerfiles-like-a-software-developer-1759f416ce84). Have you (@lindhe or @Jassob) had any experience with any similar framework?

I have not, but I like the idea of it. From the article testinfra seemed friendly enough to use. I also personally think that this kind of project is a good low-risk project where we can experience with these kinds of testing frameworks :)

**Comment by ErikThorsell** [comment]
@lindhe, any input? :)

**Comment by ErikThorsell** [comment]
@Jassob, I have removed the renaming aspects from this PR and updated the README.md accordingly.

I'll give @lindhe until the end of the day to have a look at this, thereafter I'll merge. :)

**Pull request merged**
